dotenv: .env

# automatically fetch contract sources from Etherscan
autofetch_sources: True

networks:
  default: development
  development:
    cmd_settings:
      mnemonic: ${MNEMONIC}
      default_balance: 100
      fork: https://polygon-mainnet.g.alchemy.com/v2/${ALCHEMY_PROJECT_KEY}
      chain_id: 137
    update_interval: 60
    verify: False
# my-mainnet-fork:
#   cmd_settings:
#     mnemonic: ${MNEMONIC}
#     default_balance: 100
#     fork: https://mainnet.infura.io/v3/${WEB3_INFURA_PROJECT_ID}
#   update_interval: 60
#   verify: False

# brownie networks add development polygon-main-fork-dev cmd=ganache-cli host=http://127.0.0.1 chainid=137 fork='https://polygon-mainnet.g.alchemy.com/v2/[apikey_not_shown_here]' accounts=10 mnemonic=brownie port=8545 chainid=137

# enable output of development artifacts to load with react
dev_deployment_artifacts: true

dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.3.2

compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.2"
    optimizer:
      enabled: true
      runs: 1500
